version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge